languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "Vivian Leung"
copyright = "If you're using Safari and the page isn't properly spaced, please use another browser such as Chrome or Firefox"

dateFormat = "January 02, 2006"

[author]
  name = "Vivian Leung"
  image = "../assets/profile/VYL.png"
  links = [
    { email = "mailto:vyleung@upenn.edu" },
    { github = "https://github.com/vyleung" },
    { linkedin = "https://linkedin.com/in/vyleung"},
    { twitter = "https://twitter.com/leungvyz" }
  ]
